//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastBar.MobileChallenge.Test.Responses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastBar.MobileChallenge.Test.Responses.ApiResponses", typeof(ApiResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;EventId&quot;: 12,
        ///    &quot;EventKey&quot;: &quot;demoevent001&quot;,
        ///    &quot;BarOperatorUserId&quot;: 2,
        ///    &quot;Name&quot;: &quot;Bonza Bash New Year&apos;s Eve 2015&quot;,
        ///    &quot;DateTimeStartUtc&quot;: &quot;2015-01-01T04:00:00Z&quot;,
        ///    &quot;DateTimeEndUtc&quot;: &quot;2015-01-01T10:00:00Z&quot;,
        ///    &quot;CloudinaryPublicImageId&quot;: &quot;StockEventImages/nightlife-1&quot;
        ///  },
        ///  {
        ///    &quot;EventId&quot;: 13,
        ///    &quot;EventKey&quot;: &quot;demoevent002&quot;,
        ///    &quot;BarOperatorUserId&quot;: 2,
        ///    &quot;Name&quot;: &quot;Tomato Battle Australia&quot;,
        ///    &quot;DateTimeStartUtc&quot;: &quot;2015-02-28T19:00:00Z&quot;,
        ///    &quot;DateTimeEndUtc&quot;: &quot;2015-01-29T01:00:00Z&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;access_token&quot;: &quot;5wZjoKQDzxMmN5SJo6VG-GS1gdMidplgmxM17WxyulLWY0_Ivu70TKQ2a9LvmmCLqU4S-UcVmgNTu-oCMXilNDltuNIvTATZIeQZBQzElMOY9zEYAhtRTH2UD8doX-1rqDv5bVI3wBj9xsiPP7umQlamq6lGgoIn3GZIRQN7ZHXnzVDHxJvlUiq1fEkj1OpTT7hujiGbN68hom9TCycWKeT7ZjPQVkAq5taXB4RVg_Phrz0KA6_0uLSZBxE4qEMDu332L949fPRlR5LF0hSRlk3wn7IkL80Jtj07sLa-PayLiOPhe4NvtasXErdi8zk8dZD3lhgl7zO7kwaFBzmGy4TrsflyQjBYSWBVqS0IoivxsmLOERbaFI8xMncBBCeqCqa37YNCwkDHf8oqwzjy-NPI3BbEQmT6nR8vv9Fs_aPixZS-3ZEaKPTlKGjgQvchYBz9gxBS9BzAyHLLwSpljoYTPGO7Vq9Kv-rdnSU5_SF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
    }
}
